### PR TITLE
Ported to 1.9.4 (Works on both 1.9.0 and 1.9.4)

### PR DESCRIPTION
**Pull request by GirafiStudios**
Changes:
Changed mod id to lower case (Mod IDs should ALWAYS be lower case)
Moved to GLStateManger instead of GL11
Improved buildscript. You only ever have to change versions in the gradle.properties file, to change your mod version, update Forge etc.

### CODE REVIEW

**Comment by samvbeckmann** [comment]
Awesome! I'll take a look at it after I get some sleep.

**Comment by GirafiStudios** [comment]
Sounds good! It seems like I did a lot, I barely did anything tho. The only "major" change is the buildscript, since the one you had before was well.. less functional!

**Comment by samvbeckmann** [comment]
I'll have to take a look into `GLStateManager` before merging, since it seems transparency isn't working for the day count.

**Comment by GirafiStudios** [comment]
I just tried testing the transparency issue, to see if I could reproduce. I could not :/

Proof:
clockhud1 9 4

**Comment by samvbeckmann** [comment]
Found the issue, I should have been passing transparency through the mc renderer rather than the GLStateManager. Should be working now.

**Pull request merged**
